### ISSUE TITLE
Test is failing

### ISSUE THREAD

**Issue by Charles-Ay** [ITALIA195/WuxiaReader#1]
The wuxia world test is failing. This is due to the fact that the link is 404

**Comment by novelhawk** [comment]
Thank you for your report.
Although the repository is public and not archived the code is currently unmaintained, if you are interested in making changes or using the program, feel free to fork and edit the repository to your likings with due regard to the GPL-2 license.

On another note I don't seem to be able to reproduce the error you reported, the page seems to be still accessible through the browser (https://www.wuxiaworld.com/novel/overgeared/og-chapter-18).

I'll archive the repository shortly to reflect the state of the project.

PS: This project was created for personal use only, once I stopped using it I also stopped maintaining it, that's why you see a lack of documentation and updates.
